version: '3'

services:
  app:
    build:
      context: .
    image: my_api_project
    ports:
      - "8000:9000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://db_user:db_password@db:3306/db_name
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: